#pragma once
#include <iostream>
#include <regex>
#include <ctime>
#include <algorithm>
#include <random>
#include <string>
#include <array>
#include <cstdio>
#include <cstdlib>
#include <thread>
#include <iterator>
#include <chrono>
#include <stdexcept>
#include <limits>
#include <cmath>
//#include <format>
//#include <Windows.h>
//#include <SFML/Network.hpp>
//#include <SFML/GpuPreference.hpp>
//#include <windot11.h>
using namespace std;
